<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#frmCheckoutAdapter').submit(function(ev){
			ev.preventDefault();

			var selectedAdapter = $(this).find(".checkout-adapter:checked");

			var url = '/admin/settings/config-checkout-ajax';
			var data = {
				com: 'set_adapter',
				adapter: selectedAdapter.val()
			};
			$.getJSON(
				url,
				data,
				function (reply) {
					
					if (reply.result == 'ok') {
						var element = $('#checkout_adapters li');
						var bgColor = element.css('background-color');

						element.css('background-color', '#0a0')
							.animate(
								{backgroundColor: bgColor},
								1000,
								function(){
									element.css('background-color', null)
								}
							);
					} else {
						alert(reply.desc);
					}
				}
			);
		});
	});
</script>
<form id="frmCheckoutAdapter" action="/admin/settings/config-checkout-ajax/" method="post">
	<input type="hidden" id="com" value="checkout_adapter" />
	<table cellspacing="0" cellpadding="0" border="0" class="table-data">
		<tr class="table-header">
			<th><?php echo $this->translate('Select the adapter that will handle payments');?></th>
		</tr>
		<tr class="table-row">
			<td>
				<ul class="form-list" id="checkout_adapters">
					<?php foreach ($this->adapters as $adapter):?>
					<li>
						<label><?php echo $this->translate($adapter);?></label>
						<input
							type="radio"
							name="checkout_adapter"
							class="checkout-adapter"
							<?php echo ($this->selectedAdapter == $adapter ? 'checked="checked"' : '') ?>
							value="<?php echo $adapter;?>" />
					</li>
					<?php endforeach;?>
				</ul>
			</td>
		</tr>
	</table>
	<input type="submit" value="Save" />
</form>