<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Index
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();


$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

?>
<script type="text/javascript">
<!--
jQuery(document).ready(function($){
	
	$('#frmSettings').submit(function(ev){
		ev.preventDefault();
		
		var formValues = $(this).find('input[type=text]');
		var url = '/admin/settings/config-ajax';

		/**
		 * @todo Convert formValues into proper array.
		 */
//		jQuery.each(formValues, function(i, obj){
//			alert(i + ', ' + $(obj).attr('id'));
//		});
		jQuery.post(
			url, 
			formValues, 
			function(reply) {
				
				$('#msg').html(reply.desc)
						 .show()
						 .delay(3000)
						 .slideUp();
				
			}, 
			'json'
		);
	});
});
//-->
</script>
<?php 

if (isset($vars['content'])) echo $vars['content'];

echo $this->form;
?>
<div id="msg" class="ui-corner-all ui-state-highlight" style="margin-top: 20px; padding: 1em .7em; display: none">
</div>