<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Index
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();


$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

?>
<script type="text/javascript">
<!--
jQuery(document).ready(function($){
	
	$('#frmSettings').submit(function(ev){
		ev.preventDefault();
		
		var formValues = $(this).find('textarea').val();
		var url = '/admin/settings/config-ajax';

		/**
		 * @todo Convert formValues into proper array.
		 */
//		jQuery.each(formValues, function(i, obj){
//			alert(i + ', ' + $(obj).attr('id'));
//		});
		jQuery.post(
			url, 
			{'xml' : formValues},
			function(reply) {
				if (reply.result == 'ok') {
				$('#msg').html(reply.desc)
						 .show()
						 .delay(3000)
						 .slideUp();
				} else {
					
					alert(reply.desc);
				}
				
			}, 
			'json'
		);
	});
});
//-->
</script>
<?php 

if (isset($vars['content'])) echo $vars['content'];

//echo $this->form;
?>
<div id="msg" class="ui-corner-all ui-state-highlight" style="margin-top: 20px; padding: 1em .7em; display: none">
</div>
<form action="#frmSettings" method="post" id="frmSettings">
	<ul class="form-list">
		<li><label></label><textarea cols="64" rows="42" class="monotype" style="width: 99%; float: left;"><?php echo $this->xml_string; ?></textarea></li>
		<li><input type="submit" value="Save" /></li>
	</ul>
</form>