<style type="text/css">
	
/* Vertical Tabs
----------------------------------*/
.ui-tabs-vertical { min-width: 55em; }
.ui-tabs-vertical .ui-tabs-nav { padding: .2em .1em .2em .2em; float: left; width: 12em; }
.ui-tabs-vertical .ui-tabs-nav li { clear: left; width: 100%; border-bottom-width: 1px !important; border-right-width: 0 !important; margin: 0 -1px .2em 0; }
.ui-tabs-vertical .ui-tabs-nav li a { display:block; }
.ui-tabs-vertical .ui-tabs-nav li.ui-tabs-selected { padding-bottom: 0; padding-right: .1em; border-right-width: 1px; border-right-width: 1px; }
.ui-tabs-vertical .ui-tabs-panel { padding: 1em; float: right; width: 40em;}

</style>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#settingsTabs').tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
		$("#settingsTabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	});
</script>
<div id="settingsTabs">
	<a style="float:right;" href="/admin/settings/php-environment" target="_blank"><span>PHP Environment</span></a>
	<ul>
		<li><a href="/admin/settings/overview"><span>Overview</span></a></li>
		<li><a href="/admin/settings/runmode"><span>Runmode</span></a></li>
		<li><a href="/admin/settings/security-keys"><span>Security Keys</span></a></li>
                <li><a href="/admin/settings/checkout"><span>Checkout</span></a></li>
<!--		<li><a href="/admin/settings/import"><span>Import/Export</span></a></li>-->
<!--                <li><a href="/admin/settings/xml-config"><span>XML Configuration</span></a></li>-->
<!--		<li><a href="/admin/search/"><span>Search Index</span></a></li>-->
	</ul>
</div>