<?php

$runmode = $this->runmode;
$runmodes = $this->runmodes;
?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#frmRunmode').submit(function(ev){
			ev.preventDefault();

			var runmode = $(this).find('.runmode');
			var url = '/admin/settings/config-runmode-ajax/';
			var data = {
				com: 'set_runmode',
				runmode: runmode.val()
			};

			$.getJSON(
				url,
				data,
				function(reply) {

					if (reply.result == 'ok') {
						var form = $('#frmRunmode');
						var li = form.find('.form-list li');
						var bgColor = li.css('background-color');

						li
						.css('background-color', '#0a0')
						.animate(
							{
								backgroundColor: bgColor
							},
							1000,
							function(){
								li.css('background-color', null);
							}

						);

					} else {
						alert(reply.desc);
					}
				}
			);
		});
	});
</script>
<form id="frmRunmode" method="post" action="#">
	<table cellspacing="0" cellpadding="0" border="0" class="table-data">
		<tr class="table-header">
			<th><?php echo $this->translate('Run Mode'); ?></th>
		</tr>
		<tr class="table-row">
			<td>
				<ul class="form-list">
					<li>
						<label><?php echo $this->translate("Select what mode your website should be run as");?></label>
                                                <select class="runmode">
                                                    <?php foreach($runmodes as $key => $value ): ?>
                                                    <option value="<?php echo $key; ?>" <?php echo (!empty($runmode) && $runmode == $key) ? 'selected="selected"' : '' ?>><?php echo $value; ?></option>
                                                    <?php endforeach;?>
                                                </select>
					</li>
				</ul>
			</td>
		</tr>
	</table>
	<input type="submit" value="Save" />
</form>
