<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Index
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = Zre_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

if (isset($vars['content'])) echo $vars['content'];

$logout_minutes = ((int)$settings->site->session_timeout) / 60;

$template_name = (string)$settings->site->template;

$searchIndexLinkText = $t->_('Search settings');
$aclIndexLinkText = $t->_('Acl settings');
$pluginIndexLinkText = $t->_('Plugin manager');
?>
<style type="text/css">
	
/* Vertical Tabs
----------------------------------*/
.ui-tabs-vertical { width: 55em; }
.ui-tabs-vertical .ui-tabs-nav { padding: .2em .1em .2em .2em; float: left; width: 12em; }
.ui-tabs-vertical .ui-tabs-nav li { clear: left; width: 100%; border-bottom-width: 1px !important; border-right-width: 0 !important; margin: 0 -1px .2em 0; }
.ui-tabs-vertical .ui-tabs-nav li a { display:block; }
.ui-tabs-vertical .ui-tabs-nav li.ui-tabs-selected { padding-bottom: 0; padding-right: .1em; border-right-width: 1px; border-right-width: 1px; }
.ui-tabs-vertical .ui-tabs-panel { padding: 1em; float: right; width: 40em;}

</style>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#adminTabs').tabs();
//		$('#adminTabs').tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
//		$("#adminTabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	});
</script>

<div id="adminTabs">
	<ul>
		<li><a href="/admin/settings" title="system-tab"><span>System</span></a></li>
		<li><a href="/admin/acl" title="acl-tab"><span>ACL</span></a></li>
		<li><a href="/admin/users" title="users-tab"><span>Users</span></a></li>
                <li><a href="/admin/images" title="images-tab"><span>Images</span></a></li>
		<li><a href="/admin/articles" title="articles-tab"><span>Articles</span></a></li>
                <li><a href="/admin/products" title="products-tab"><span>Products</span></a></li>
		<li><a href="/admin/orders" title="orders-tab"><span>Orders</span></a></li>
		
		
	</ul>
</div>
<?php 
// Check for plugins
//echo Plugin::inject($output);
//
//echo $output;

echo $this->form;
?>