<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. All rights reserved.
 * @license Creative Commons license - See public/license.txt
 */
$vars = $this->getVars();
$params = $vars['params'];

$name_id = null;
$aclResource = new Zre_Dataset_Acl_Resource();
$data = $aclResource->listAll( null, array('order' => 'acl_resource_id ASC') );

echo Zend_Json::encode( $data );
?>