<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];

$id = $params['id'];
$aclResource = new Zre_Dataset_Acl_Resource();
$rows = Zre_Dataset_Acl_Resource::read( $id );

echo Zend_Json::encode( $rows );
?>