<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];
$aclRole = new Zre_Dataset_Acl_Role();
if (isset($params['id'])) {
	echo (int)$aclRole->delete('acl_role_id = ?', $params['id'] );
}
?>