<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];

$name_id = null;

$aclRole = new Zre_Dataset_Acl_Role();
$data = $aclRole->listAll(null, array('order' => 'acl_role_id ASC'));

foreach($data as $index => $entry) {
	if (isset($entry['parents'])) {
		$data[$index]['parents'] = unserialize($entry['parents']);
	}
}

echo Zend_Json::encode( $data );
?>