<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];

$id = $params['id'];
$aclRole = new Zre_Dataset_Acl_Role();
$rows = $aclRole->read( $id );

foreach($rows as $index => $entry) {
	if (isset($entry['parents'])) {
		$rows[$index]['parents'] = unserialize($entry['parents']);
	}
}

echo Zend_Json::encode( $rows );
?>