<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];
$aclResource = new Zre_Dataset_Acl_Resource();
echo (int)$aclResource->create( $params );
?>