<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
$params = $vars['params'];

if (isset($params['id'])) {
	$aclAllow = new Zre_Dataset_Acl_Allow();
	echo (int)$aclAllow->delete('acl_allow_id = ?', $params['id'] );
}
?>