<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Acl
 * @category Views
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. All rights reserved.
 * @license Creative Commons license - See public/license.txt
 */
$vars = $this->getVars();
$params = $vars['params'];
Debug::mail(print_r($params, true));
$aclResource = new Zre_Dataset_Acl_Resource();
echo Zend_Json::encode($aclResource->update( $params, $params['id'] ));
?>