<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Acl
 * @subpackage Acl
 * @category Acl
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. All rights reserved.
 * @license Creative Commons license - See public/license.txt
 */

$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title,Zend_View_Helper_Placeholder_Container_Abstract::SET );
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = isset($vars['params']) ? $vars['params'] : null;

$nameValue = null;
if (isset($params['name'])) $nameValue = $params['name'];
$aclAllow = new Zre_Dataset_Acl_Allow();
$aclResources = new Zre_Dataset_Acl_Resource();

$aclRules = $aclAllow->listAll(
	isset($nameValue) ? array('name' => $nameValue) : null, 
	array('order' => 'acl_allow_id ASC')
);
$aclResources = $aclResources->listAll(null, array('order' => 'acl_resource_id ASC'));

$aclPrivileges = array('new', 'view', 'update', 'remove', 'publish', 'archive', 'ALL', 'NONE');
$ruleJs = array();
$ruleIdJs = array();
$ruleResourcesJs = array();
$rulePrivilegesJs = array();
$allResourcesJs = array();
$allPrivilegesJs = $aclPrivileges;

?>
<h1><?php echo $t->_('Allow ACL Rules')?></h1>
<form id="frmAllowRules" method="post">
<h3><?php echo $t->_('Role')?></h3>
<?php
$selectBoxRoles = '<select id="acl_allow_role">' . "\n"; 
$defaultResources = '';
$defaultPrivileges = '';

foreach($aclRules as $index => $rule) {
	
	$rule['resources'] = unserialize($rule['resources']);
	$rule['privileges'] = unserialize($rule['privileges']);
	
	$selectBoxRoles .= '<option value="' . $rule['acl_allow_id'] . '">' . $rule['name'] . '</option>' . "\n";
	
	if ($index == 0) {
		$dontAddResources = array();
		$i = 0;
		if (!empty($rule['resources']) && count($rule['resources']) > 0) {
			
			foreach($rule['resources'] as $i => $resource) { 
				$defaultResources .= '<input type="checkbox" checked="checked" id="acl_allow_resources_' . $i . '" name="acl_allow_resources[]" value="' . $resource . '" /><label for="acl_allow_resources_' . $i . '">' . $resource . '</label><br />' . "\n";
				$dontAddResources[] = $resource;
			}
			$i += 1;
		}
		
		foreach($aclResources as $j => $otherResource) {
			$resource = $otherResource['name'];
			$allResourcesJs[] = $resource;
			if ( !in_array($resource, $dontAddResources) ) {
				$defaultResources .= '<input type="checkbox" id="acl_allow_resources_' . ($i + $j) . '" name="acl_allow_resources[]" value="' . $resource . '" /><label for="acl_allow_resources_' . ($i + $j) . '">' . $resource . '</label><br />' . "\n";
			}
		}
		$i = 0;
		if (!empty($rule['privileges']) && count($rule['privileges']) > 0) {
			foreach($rule['privileges'] as $i => $privilege) {
				$defaultPrivileges .= '<input type="checkbox" checked="checked" id="acl_allow_privileges_' . $i . '" name="acl_allow_privileges[]" value="' . $privilege . '" /><label for="acl_allow_privileges_' . $i . '">' . $privilege . '</label><br />' . "\n";
			}
			$i += 1;
		}
		$thePrivileges = !empty($rule['privileges']) ? $rule['privileges'] : array();
		foreach($aclPrivileges as $j => $privilege) {
			if (!in_array($privilege, $thePrivileges)) {
				$defaultPrivileges .= '<input type="checkbox" id="acl_allow_privileges_' . ($i + $j) . '" name="acl_allow_privileges[]" value="' . $privilege . '" /><label for="acl_allow_privileges_' . ($i + $j) . '">' . $privilege . '</label><br />' . "\n";
			}
		}
	}
	
	$ruleJs[] = "\tarrRules['" . $rule['acl_allow_id'] . "'] = '" . $rule['name'] . "';";
	$ruleIdJs[] = "\tarrRuleIds['" . $rule['name'] . "'] = '" . $rule['acl_allow_id'] . "';";
	
	$resources = ($rule['resources'] ? Zend_Json::encode($rule['resources']) : "null");
	$privileges = ($rule['privileges'] ? Zend_Json::encode($rule['privileges']) : "null");
	
	$ruleResourcesJs[] = "\tarrRuleResources['" . $rule['name'] . "'] = " . $resources . ";";
	$rulePrivilegesJs[] = "\tarrRulePrivileges['" . $rule['name'] . "'] = " . $privileges . ";";
	
}
$selectBoxRoles .= '</select>';
 
$ruleJs = implode("\n", $ruleJs);
$ruleIdJs = implode("\n", $ruleIdJs);
$ruleResourcesJs = implode("\n", $ruleResourcesJs);
$rulePrivilegesJs = implode("\n", $rulePrivilegesJs);
$allResourcesJs = Zend_Json::encode($allResourcesJs);
$allResourcesJs = $allResourcesJs ? "$allResourcesJs;" : 'new Array();';
$allPrivilegesJs = Zend_Json::encode($allPrivilegesJs);
$allPrivilegesJs = $allPrivilegesJs ? "$allPrivilegesJs;" : 'new Array();';
?>
<script type="text/javascript">
jQuery(document).ready(function($){
	var arrRules = new Array();
<?php echo $ruleJs; ?>

	var arrRuleIds = new Array();
<?php echo $ruleIdJs; ?>

	var arrRuleResources = new Array();
<?php echo $ruleResourcesJs; ?>

	var arrRulePrivileges = new Array();
<?php echo $rulePrivilegesJs; ?>
	
	var arrAllResources = <?php echo $allResourcesJs; ?>
	
	var arrAllPrivileges = <?php echo $allPrivilegesJs; ?>
		
	$("#btnUpdateAclAllow").click(function(){
		
		roleId = $("#acl_allow_role").attr("value");
		roleResources = [];
		rolePrivileges = [];
		
		allResources = $("input[name='acl_allow_resources[]']");
		allPrivileges = $("input[name='acl_allow_privileges[]']");
		
		var index = 0;
		allResources.each(function(i, obj) {
			if ( $(obj).attr('checked') == true ) {
				roleResources[index] = $(obj).val();
				index++;
			}
		});
		index = 0;
		allPrivileges.each(function(i, obj) {
			if ( $(obj).attr('checked') == true ) {
				rolePrivileges[index] = $(obj).val();
				index++;
			}
		});
		
		$.getJSON(
			"/admin/acl/ajax.allow.update/" , 
			{
				id: roleId,
				resources: roleResources,
				privileges: rolePrivileges
			}, 
		function(j) {
			
			if (j == 1) {
				refreshAclAllowRoleList();
			} else {
				alert("Error: Could not update. Result: " + j);
			} 
			
		})
	});
	
	$('#acl_allow_role').change(
		function () {
			var selectedValue = $("select#acl_allow_role option:selected").attr("value");
			var selectedText = $("select#acl_allow_role option:selected").text();
			
			var resources = arrRuleResources[selectedText];
			var privileges = arrRulePrivileges[selectedText];
			
			var strResourcesOptions = '';
			var strPrivilegesOptions = '';
			
			$('#acl_allow_resources_container').html('');
			$('#acl_allow_privileges_container').html('');
			
			var lastResourceCount = 0;
			var i = 0;
			for (i in resources) {
				strResourcesOptions += '<input id="acl_allow_resources_' + i + '" checked="checked" name="acl_allow_resources[]" type="checkbox" value="' + resources[i] + '"><label for="acl_allow_resources_' + i + '">' + resources[i] + '</label><br />' + "\n";
				
			}
			i += 1;
			var isInArray = false;
			var resourcesLen = arrAllResources.length;
			
			for (var j in arrAllResources) {
				isInArray = false;
				if (resources && resources.length > 0) {
					for (var k in resources) {
						
						if (arrAllResources[j] == resources[k]) isInArray = true;
					}
				}
				if (isInArray == false) {
					strResourcesOptions += '<input id="acl_allow_resources_' + (i + j) + '" name="acl_allow_resources[]" type="checkbox" value="' + arrAllResources[j] + '"><label for="acl_allow_resources_' + (i + j) + '">' + arrAllResources[j] + '</label><br />' + "\n";
				}
			}
			
			for (var i in privileges) {
				strPrivilegesOptions += '<input id="acl_allow_privileges_' + i + '" checked="checked" name="acl_allow_privileges[]" type="checkbox" value="' + privileges[i] + '"><label for="acl_allow_privileges_' + i + '">' + privileges[i] + '</label><br />' + "\n";
			}
			i += 1;
			for (var j in arrAllPrivileges) {
				isInArray = false;
				if (privileges && privileges.length > 0) {
					for (var k in privileges) {
						
						if (arrAllPrivileges[j] == privileges[k]) isInArray = true;
					}
				}
				if (isInArray == false) {
					strPrivilegesOptions += '<input id="acl_allow_privileges_' + (i + j) + '" name="acl_allow_privileges[]" type="checkbox" value="' + arrAllPrivileges[j] + '"><label for="acl_allow_privileges_' + (i + j) + '">' + arrAllPrivileges[j] + '</label><br />' + "\n";
				}
			}
			
			$('#acl_allow_resources_container').html(strResourcesOptions);
			$('#acl_allow_privileges_container').html(strPrivilegesOptions);
		}
	);
	
	function refreshAclAllowRoleList() {
		$("#acl_allow_role").hide();
		$("#acl_allow_role_properties").hide();
		$.getJSON("/admin/acl/ajax.allow.list/", {}, function(data) {
			
			arrRules = new Array();
			arrRuleIds = new Array();
			arrRuleResources = new Array();
			arrRulePrivileges = new Array();
			
			for(var i = 0; i < data.length; i++) {
				
				arrRules[data[i].acl_allow_id] 	= data[i].name;
				arrRuleIds[data[i].name] 		= data[i].acl_allow_id;
				arrRuleResources[data[i].name] 	= data[i].resources;
				arrRulePrivileges[data[i].name] = data[i].privileges;
			}
			
			$('#acl_allow_role').change();

			$("#acl_allow_role").show();
			$("#acl_allow_role_properties").show();
		});
	}
});
</script>
<?php echo $selectBoxRoles; ?>
<br />
<table cellspacing="0px" cellpadding="0px" border="0px" id="acl_allow_role_properties">
	<tr>
		<td style="vertical-align: top; padding-left: 12px;">
			<h3><?php echo $t->_('Resources');?></h3>
			<div id="acl_allow_resources_container">
			<?php echo $defaultResources;?>
			</div>
		</td>
		<td style="vertical-align: top; padding-left: 16px;">
			<h3><?php echo $t->_('Privileges');?></h3>
			<div id="acl_allow_privileges_container">
			<?php echo $defaultPrivileges;?>
			</div>
		</td>
	</tr>
</table>
<br />
	<input type="button" id="btnUpdateAclAllow" value="<?php echo $t->_('Update')?>" />
</form>