<?php
if (isset($this->content)) {
	?><div id="message" class="errors"><?php echo $this->content;?></div><?php 
}
$d = array();
if (isset($this->data)) $d = $this->data;

$fields = $this->fields;

?>

<form action="/shop/checkout" method="post">
	<ul class="form-list">
		<?php
		foreach ($fields as $key => $value):
			
			
			if (is_array($value['type'])) {
		?>
		<li>
			<label><?php echo $this->translate($value['label']);?></label>
			<select name="<?php echo $key;?>">
				<?php
				foreach($value['type'] as $v => $option):
					?>
				<option value="<?php echo $v;?>"><?php echo $this->translate($option);?></option>
					<?php
				endforeach;
				?>
			</select>
		</li>
		<?php
				} else {
		?>
		<li>
			<?php if (!empty($value['label'])):?>
			<label><?php echo $this->translate($value['label']);?></label>
			<?php 
			    endif;
			    switch ($value['type']):
				case 'text':
			?>
			<input type="text" name="<?php echo $key;?>" value="<?php echo isset($d->{$key}) ? $d->{$key} : '';?>" />
			<?php	    break;?>

			<?php	case 'image':?>
			<input type="image" name="<?php echo $key;?>" src="<?php echo isset($value['url']) ? $value['url'] : '';?>" alt="<?php echo $key ?>" />
			<?php	    break;?>

			<?php	case 'hidden':?>
			<input type="hidden" name="<?php echo $key;?>" value="<?php echo isset($d->{$key}) ? $d->{$key} : isset($value['value']) ? $value['value'] : '';?>" />
			<?php	    break;?>

			<?php	case 'image_link':?>
			<a href="<?php echo isset($value['href']) ? $value['href'] : '';?>" name="<?php echo $key;?>"><img src="<?php echo isset($value['url']) ? $value['url'] : '';?>" alt="<?php echo $key ?>" /></a>
			<?php	    break;?>

			<?php	case 'submit':?>
			<input type="submit" name="<?php echo $key; ?>" value="<?php echo !empty($value['value']) ? $this->translate($value['value']) : $this->translate('Submit') ?>" />
			<?php	    break;?>

			<?php endswitch;?>
		</li>
		<?php
			}
			
		endforeach;?>
	</ul>
</form>