<?php
/**
 * ZRECommerce e-commerce web application.
 *
 * @author ZRECommerce
 *
 * @package Admin
 * @subpackage Products
 * @category Core
 *
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();


$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

$strStatus	= 'Published';
$strDeliveryMethod = 'Delivery Method';
$strDeliveryMethods = '<option value="">None</option>';

foreach($this->logistic_adapters as $adapter) {
    $strDeliveryMethods .= '<option value="' . $adapter . '">' . $this->translate($adapter) . '</option>';
}

$strYes		= $this->translate('Yes');
$strNo		= $this->translate('No');
$strArchived	= $this->translate('Archived');
$strUpdateProduct = $this->translate('Update Product');

$strInternalError = $this->translate('There was an internal error.');

// Content
if (isset($vars['content'])) echo $vars['content'];
?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('#product_option_dialog').dialog({
		    autoOpen: false,
		    modal: true,
		    buttons: {
			"<?php echo $this->translate('Create Option');?>": function() {
			    var productId = $(this).find('#target_product_id');
			    var key = $(this).find('#target_product_option_key');
			    var value = $(this).find('#target_product_option_value');

			    var data = {
				product_id: productId.val(),
				key: key.val(),
				value: value.val()
			    };

			    productId.val('');
			    key.val('');
			    value.val('');

			    jQuery.getJSON(
				'/admin/product-options/json-create',
				data,
				function (reply) {
				    if (reply.result == 'ok') {
					reloadOptions(data.product_id);
				    } else {
					alert(reply.data);
				    }
				}
			    );

			    $(this).dialog('close');
			},
			"<?php echo $this->translate('Cancel');?>": function() {
			    var productId = $(this).find('#target_product_id');
			    var key = $(this).find('#target_product_option_key');
			    var value = $(this).find('#target_product_option_value');

			    productId.val('');
			    key.val('');
			    value.val('');

			    $(this).dialog('close');
			}
		    }
		});

		function rebindRemoveOptionButton() {
		    $('#frmProducts .remove-option').click(function(ev){
			var id = $(this).attr('id').replace('product_remove_option_', '');
			jQuery.getJSON(
			    '/admin/product-options/json-delete',
			    {
				option_id: id
			    },
			    function(reply) {
				if (reply.result == 'ok' && reply.data > 0) {
				    $('#product_option_li_' + id).remove();
				} else {
				    alert(reply.data);
				}
			    }
			);
		    });
		}

		function reloadOptions(product_id) {
		    // Reload product options here.
		    jQuery.getJSON(
			'/admin/product-options/json-list/',
			{
			    product_id: product_id
			},
			function (reply) {
			    var ul = $('#product_options_' + product_id + ' .form-list');

			    if (reply.result == 'ok') {
				ul.html('');
				if (reply.data != null) {
				    jQuery.each(reply.data, function (i, obj) {
					ul.append(
					    '<li id="product_option_li_' + obj.option_id +'"><label>' + obj.key + '</label><input id="product_option_' + obj.key + '" type="text" value="' + obj.value + '" /><button class="remove-option" id="product_remove_option_' + obj.option_id + '"><?php echo $this->translate('Remove');?></button></li>'
					);
				    });

				    rebindRemoveOptionButton();
				}
			    } else {
				alert(reply.data);
			    }
			}
		    );
		}

		function renderTable(response) {

			$('#frmProducts .table-data .table-body').remove();

			$.each(response.data, function(i, row){

				$('#frmProducts .table-data').append(
				'<tbody class="table-body">' +
					'	<tr class="table-row">' +
					'		<td>' + row.product_id + '</td>' +
					'		<td>' + row.title + '</td>' +
					'		<td>' + row.price + '</td>' +
					'		<td>' + row.allotment + '</td>' +
					'		<td>' + row.pending + '</td>' +
					'		<td>' + row.sold + '</td>' +
					'		<td id="product_status_label_' + row.product_id + '">' + row.published + '</td>' +
					'	</tr>' +
					'	<tr class="table-sub-row">' +
					'		<td colspan="7">' +
					'			<ul class="text-right no-bullets">' +
					'				<li><span class="float-box-left">Product #' + row.product_id + ': </span><span><input type="text" class="product-title" id="product_title_' + row.product_id + '" value="' + row.title + '" /></span></div>' +
					'				<li><span class="float-box-left">Allotment: </span><span><input type="text" class="product-allotment" id="product_allotment_' + row.product_id + '" value="' + row.allotment + '" /></span></div>' +
					'				<li><span class="float-box-left">Price: </span><span><input type="text" class="product-price" id="product_price_' + row.product_id + '" value="' + row.price + '" /></span></div>' +
					'				<li>' +
					'				<span class="float-box-left"><?php echo $strDeliveryMethod;?>: </span>' +
					'				    <select class="product-delivery-method-select" id="product_delivery_method_' + row.product_id + '">' +
					'					' + '<?php echo $strDeliveryMethods;?>' +
					'				    </select>' +
					'				</li>' +
					'				<li>' +
					'				<span class="float-box-left"><?php echo $strStatus;?>: </span>' +
					'					<select class="product-published-select" id="product_published_' + row.product_id + '">' +
					'						<option value="yes"><?php echo $strYes;?></option>' +
					'						<option value="no"><?php echo $strNo;?></option>' +
					'						<option value="archived"><?php echo $strArchived;?></option>' +
					'					</select>' +
					'				</li>' +
					'			</ul>' +
					'			<div class="editor" id="product_description_' + row.product_id + '">' + row.description + '</div>' +
					'			<div class="product-options-controls">' +
					'			    <?php echo $this->translate('Options:');?>' +
					'			    <button class="add-option" id="product_add_option_' + row.product_id + '"><?php echo $this->translate('Add');?></button>' +
					'			</div>' +
					'			<div class="product-options" id="product_options_' + row.product_id + '">' +
					'			    <ul class="form-list">' +
					'			    </ul>' +
					'			</div>' +
					'		</td>' +
					'	</tr>' +
					'</tbody>'
				);

				$('#frmProducts #product_status_' + row.product_id + ' option[value=' + row.status + ']').attr('selected', 'selected');
				$('#frmProducts #product_delivery_method_' + row.product_id + ' option[value=' + row.delivery_method + ']').attr('selected', 'selected');
				$('#frmProducts #product_status_label_' + row.product_id).html(row.status);

				// Load up product options, if any
				$('#frmProducts .add-option').click(function(ev){
				    var id = $(this).attr('id').replace('product_add_option_', '');
				    $('#product_option_dialog').find('#target_product_id').val(id);
				    $('#product_option_dialog').dialog('open');
				});

				reloadOptions(row.product_id);
			});

			rebindProductEditors();
		}

		$('#frmProducts').tableSort({
			pageIndex: 1,
			rowCount: 5,
			onJsonSuccess: renderTable
		});

		function rebindProductEditors() {

			$('#frmProducts .table-data .editor').each(function (i, obj) {
				var content = $(obj).html();
				$(obj).wymeditor({
					html: content,
					postInit: function(wym) {

						//construct the button's html
						var html = "<li class='wym_tools_newbutton'>"
							+ "<a name='SaveButton' href='#'"
							+ " style='background-image:"
							+ " url(/scripts/jquery/wymeditor/skins/default/icons.png); background-position: 0px -" + (26 * 24) + "px;' title='Save'>"
							+ "Save"
							+ "</a></li>";

						//add the button to the tools box
						jQuery(wym._box)
							.find(wym._options.toolsSelector + wym._options.toolsListSelector)
							.prepend(html);

							//handle click event
							jQuery(wym._box)
								.find('li.wym_tools_newbutton a').click(function() {
									//do something
									var htmlData = wym.html();
									var product_id = jQuery(this).parent().parent().parent().parent().parent().parent().find('.editor').attr('id').replace('product_description_', '');
									var product_title = jQuery('#product_title_' + product_id).val();
									var product_published = $('#product_published_' + product_id).val();
									var product_allotment = $('#product_allotment_' + product_id).val();
									var product_price = $('#product_price_' + product_id).val();
									var product_delivery_method = $('#product_delivery_method_' + product_id).val();

									var subRow = $('#product_description_' + product_id).parent().parent();
									var row = subRow.prev();

									row.find('.product_title').html(product_title);

									jQuery.getJSON(
										'/admin/products/json-update',
										{
											product_id: product_id,
											description: htmlData,
											title: product_title,
											published: product_published,
											allotment: product_allotment,
											price: product_price,
											delivery_method: product_delivery_method
										},
										function (reply) {
											var responseColor = '';
											var subRow = $('#product_description_' + reply.product_id).parent().parent();
											var row = subRow.prev();

											if (reply.result == 'ok') {
												responseColor = '#0c0';
												row.find('.product_date_created').html('<div>' + reply.date_created + '</div><div class="small-text">' + reply.date_modified + '</div>');
												row.find('.product_price').html(reply.price);
												row.find('.product_allotment').html(reply.allotment);
											} else {
												responseColor = '#c00';
												$('#product_msg_dialog').show().html('<div class="ui-state-error ui-corner-all">' + reply.data + '</div>').delay(5000).fadeOut();
											}
											var bgColor = subRow.css('background-color');

											subRow.css('background-color', responseColor);
											subRow.animate({backgroundColor: bgColor}, 3000, function(){
												$('#frmProducts').tableSort('load', null);
											});
										}
									);

									return(false);
								});
					}
				});
			});
		}

		$('#new_product_description').wymeditor({
			postInit: function(wym) {

				//construct the button's html
				var html = "<li class='wym_tools_newbutton'>"
					+ "<a name='SaveButton' href='#'"
					+ " style='background-image:"
					+ " url(/scripts/jquery/wymeditor/skins/default/icons.png); background-position: 0px -" + (26 * 24) + "px;' title='Save'>"
					+ "Save"
					+ "</a></li>";

				//add the button to the tools box
				jQuery(wym._box)
				.find(wym._options.toolsSelector + wym._options.toolsListSelector)
				.prepend(html);

				//handle click event
				jQuery(wym._box)
				.find('li.wym_tools_newbutton a').click(function() {
					//do something
					var htmlData = wym.html();

					var product_title = jQuery('#new_product_title').val();
					var product_image = jQuery('#new_product_image').val();
					var allotment = jQuery('#new_product_allotment').val();
					var published = jQuery('#new_product_published').val();
					var price = jQuery('#new_product_price').val();
					var delivery_method = jQuery('#new_product_delivery_method').val();

					jQuery.getJSON(
					'/admin/products/json-create',
					{
						description: htmlData,
						title: product_title,
						image: product_image,
						published: published,
						price: price,
						allotment: allotment,
						delivery_method: delivery_method
					},
					function (reply) {
					
						if (reply > 0) {

						    var el = $('#frmNewProduct li');
						    var bg = el.css('background-color');

						    el.css('background-color', '#0a0').animate({backgroundColor: bg}, 1000, function(){});

						    $('#frmProducts').tableSort('load', null);
						} else {
							alert('<?php echo $strInternalError; ?>');
						}
					}
				);

					return(false);
				});
			}
		});
	});
</script>
<div id="product_option_dialog" title="<?php echo $this->translate('Options');?>" style="display: none;">
    <input type="hidden" id="target_product_id" value="" />
    <ul class="form-list">
	<li><label>Key:</label><input type="text" id="target_product_option_key" value="" /></li>
	<li><label>Value:</label><input type="text" id="target_product_option_value" value="" /></li>
    </ul>
</div>
<div id="product_msg_dialog"></div>
<form id="frmProducts" action="/admin/products/json.list">
	<table cellspacing="0" cellpadding="0" border="0" class="table-data">
		<tr class="table-header">
			<th><a href="product_id"><?php echo $this->translate('ID'); ?></a></th>
			<th><a href="title"><?php echo $this->translate('Title'); ?></a></th>
			<th><a href="price"><?php echo $this->translate('Price'); ?></a></th>
			<th><a href="allotment"><?php echo $this->translate('Left'); ?></a></th>
			<th><a href="pending"><?php echo $this->translate('Pending'); ?></a></th>
			<th><a href="sold"><?php echo $this->translate('Sold'); ?></a></th>
			<th><a href="published"><?php echo $this->translate('Enabled'); ?></a></th>
		</tr>
	</table>
</form>
<br />
<br />
<h3><?php echo $this->translate('Create a new product'); ?></h3>
<div id="frmNewProduct">
	<ul class="form-list">
		<li>
			<label for="new_product_title"><?php echo $this->translate('Title'); ?></label>
			<input type="text" id="new_product_title" value="" />
		</li>
		<li>
			<label for="new_product_image"><?php echo $this->translate('Image'); ?></label>
			<input type="text" id="new_product_image" value="/images/dummy.png" />
		</li>
		<li>
			<label for="new_product_allotment"><?php echo $this->translate('Allotment'); ?></label>
			<input type="text" id="new_product_allotment" value="0" />
		</li>
		<li>
			<label for="new_product_article_id"><?php echo $this->translate('Article'); ?></label>
			<select id="new_product_article_id">
				<?php
				if ($this->articles->count() > 0):
					foreach($this->articles as $a):
						?>
				<option value="<?php echo $a->article_id;?>"><?php echo $a->title;?></option>
					<?php
					endforeach;
				else:
					?>
				<option value="">None</option>
				<?php
				endif;
				?>
			</select>
		</li>
		<li>
			<label for="new_product_published"><?php echo $this->translate('Published'); ?></label>
			<select id="new_product_published">
				<option value="yes"><?php echo $this->translate('Yes');?></option>
				<option value="no" selected="selected"><?php echo $this->translate('No');?></option>
				<option value="archived"><?php echo $this->translate('Archived');?></option>
			</select>
		</li>
		<li>
			<label for="new_product_price"><?php echo $this->translate('Price'); ?></label>
			<input type="text" id="new_product_price" value="0.00" />
		</li>
		<li>
		    <label>Shipping method</label>
		    <select id="new_product_delivery_method">
			<?php echo $strDeliveryMethods;?>
		    </select>
		</li>
	</ul>
	<div id="new_product_description"></div>
</div>