<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Products
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();


$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

// Content
if (isset($vars['content'])) echo $vars['content'];

// Listing
$header_map = array(
	'id' 			=> 'ID',
	'container_id' 	=> 'Parent',
	'title' 		=> 'Title',
	'description' 	=> 'Description',
	'price' 		=> 'Price',
	'allotment' 	=> 'Allot.',
	'pending' 		=> 'Pending',
	'sold' 			=> 'Sold',
	'published'		=> 'Live'
);

$exclude_map = array(
	'id',
	'container_id',
	'date_created',
	'date_modified',
);
$product = new Zre_Dataset_Product();

//echo $this->paginationControl( $datagrid->paginator, 'Sliding', '/products/pagination_control.phtml');
//
//echo $this->form;
?>

<table cellspacing="0" cellpadding="0" border="0" class="table-data">
	<tr class="table-header">
		<th>ID</th>
		<th>Title</th>
		<th>Description</th>
		<th>Price</th>
		<th>Left</th>
		<th>Sold</th>
		<th>Enabled</th>
	</tr>
	<?php foreach($product->listAll(null, array('order' => 'title ASC'), false) as $p):?>
	<tr class="table-row">
		<td><?php echo $p->product_id;?></td>
		<td><?php echo $p->title;?></td>
		<td><img src="<?php echo $p->image;?>" alt="<?php echo $p->title;?>" style="float:left; margin-right: 0.4em; margin-bottom: 0.4em;" /><?php echo $p->description;?></td>
		<td><?php echo $p->price;?></td>
		<td><?php echo $p->allotment;?></td>
		<td><?php echo $p->sold;?></td>
		<td><?php echo $p->published;?></td>
	</tr>
	<?php endforeach;?>
</table>