<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Product
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$settings = ZRE_Config::getSettingsCached();


$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

if (isset($vars['enable_dojo']) && $vars['enable_dojo'])
{
	$this->dojo()->enable()
		->setDjConfigOption('parseOnLoad', true);
}
if (isset($vars['content'])) echo $vars['content'];

// Menu
$config = array(
	'All' => 		array('id'=>'mnuAdminProductAll', 'class'=>'menuItem', 'url'=>'/admin/products/'),
	'New' => 		array('id'=>'mnuAdminProductNew', 'class'=>'menuItem', 'url'=>'/admin/products/new/'),
	'Categories' =>		array('id'=>'mnuAdminProductCategories', 'class'=>'menuItem', 'url'=>'/admin/products/categories/')
);

echo new Zre_Ui_Menu('mnuOptions', $config);

echo $this->form;
?>