<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Layout
 * @category Default
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$vars = $this->getVars();
if (isset($vars['right_column']) && is_array($vars['right_column']))
{
	foreach($vars['right_column'] as $item)
	{
		echo $item;
	}
}
?>