<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Articles
 * @subpackage Articles_Read
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$settings = ZRE_Config::getSettingsCached();

$articleData = $this->data;

$articleTitleText = $articleData['title'];

$this->headTitle($articleTitleText . (string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

Plugin::setView($this);

if (isset($this->content)) echo $this->content;

	$articleId 			= $articleData['article_id'];
	$articleContainerId = $articleData['article_container_id'];
	$articleResource 	= $articleData['resource'];
	$articlePublished 	= $articleData['published'];
	$articleTitle 		= stripslashes($articleData['title']);
	$articleDescription = stripslashes($articleData['description']);
	$articleDateCreated  = new Zend_Date( $articleData['date_created'] );
	$articleDateModified = new Zend_Date( $articleData['date_modified'] );
	$articleImage 		= $articleData['image'];
	
	if (!$articleImage) $articleImage = '/images/dummy.png';

	$articleDescription = str_replace(array('{%', '%}', '\"'), array('<', ' article_id="' . $articleId . '" />', '"'), $articleDescription);

        /**
         * @todo this should really be generated in the admin area.
         */
	$titleSlug = Zre_Template::createSlug($articleTitle);
?>
<div class="articleContainer">
	<table cellspacing="0" cellpadding="0" border="0" class="articleContainerInner">
		
		<tr>
			<td class="articleImageCell">
				<img src="<?php echo $articleImage; ?>" alt="<?php echo $articleTitle; ?>" class="articleImage" />
			</td>
			
			<td class="articleText">
				<h1 class="articleTitle">
					<?php echo $articleTitle; ?>
				</h1>
				<div class="articleDescription">
				<?php echo Plugin::inject($articleDescription); ?>
				</div>
				<div class="articleFooter"><?php echo $this->translate('Last edited ') . $articleDateCreated->getArpa(); ?></div>
			</td>
		</tr>
	</table>
</div>