<?php 
$dest = 'C:\Users\Alex\Desktop\backup.tgz';
Zre_File::compress(
	array(	'../application/settings/database/mysql/default.sql',
			'../application/settings/database/sqlite/aclResources.sq3',
			'../application/settings/database/sqlite/articleResourceType.sq3',
			'../application/settings/database/sqlite/plugins.sq3',
			'../application/settings/environment/settings.xml' ),
	$dest);
	
	
Zre_File::decompress($dest, "C:\\Users\\Alex\\Desktop\\backup-tgz\\");