<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Articles
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title,Zend_View_Helper_Placeholder_Container_Abstract::SET );
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = isset($vars['params']) ? $vars['params'] : null;

// See if we have any listing parameters.		
$start_index = isset($params['start_index']) ? $params['start_index'] : 0;
$max_per_page = isset($params['max_per_page']) ? $params['max_per_page'] : 10;

// Grab our key/value POST vars, for use with our datagrid links.

$url_params = '/start_index/'. $start_index . '/max_per_page/' . $max_per_page;

// Content
if (isset($vars['content'])) echo $vars['content'];

// Listing
$header_map = array(
	'article_id' 			=> 'ID',
	'article_container_id' 	=> 'Category',
	'resource' 		=> 'Type',
	'published' 	=> 'Published',
	'title' 		=> 'Title',
	'date_created' 	=> 'Created',
	'date_modified' => 'Modified'
);

$format_map = array(
	'description' => ENT_QUOTES
);

$exclude_map = array(
	'article_id',
	'article_container_id',
	'date_modified',
	'image'
);

$strTitle = $t->_('Title: ');
$strInternalError = $this->translate('Internal error.');

$categories = new Zre_Dataset_Article_Container();
$categoryData = $categories->listAll(
	array(
	    'parent_id' => array(
		'operator' => 'IS',
		'value' => new Zend_Db_Expr('NULL')
	    )
	),
	array(
	    'order' => 'order_weight ASC',
	    'order ' => 'title ASC'
	),
	false
);

$rootCategories = array();
$childCategories = array();

foreach ($categoryData as $row) {
    $childCategories[] = array(
	'data' => $row->title,
	'attr' => array(
	    'id' => 'category_' . $row->article_container_id,
	    'parent_id' => !empty($row->parent_id) ? $row->parent_id : ''
	),
	'state' => 'closed',
	'icon' => 'folder'
    );
}

$rootCategories = array(
    'data' => '(Root)',
    'attr' => array(
	'id' => 'category_0',
	'parent_id' => '',
    ),
    'state' => 'open',
    'icon' => 'folder',
    'children' => $childCategories
);
?>
<script type="text/javascript" src="/scripts/jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="/scripts/jquery/jstree/jquery.jstree.js"></script>
<script type="text/javascript">
	jQuery(document).ready(function($){
		function renderTable(response)
		{
			var strYes = '<?php echo $this->translate('Yes');?>';
			var strNo = '<?php echo $this->translate('No');?>';
			var strArchived = '<?php echo $this->translate('Archived');?>';
			// Clear out the existing HTML table data.
			$('#frmArticles .table-data .table-body').remove();

			// Fill the HTML table with the new data.
			$.each(response.data, function(i, row){
				
				$('#frmArticles .table-data').append(
					'<tbody class="table-body">' + 
					'	<tr class="table-row">' + 
					'		<td class="article_date_created"><div>' + row.date_created + '</div><div class="small-text">Modified: ' + row.date_modified + '</div></td>' +
					'		<td class="article_title">' + row.title + '</td>' +
					'	</tr>' +
					'	<tr class="table-sub-row">'  +
					'		<td colspan="2"><ul class="form-list">' +
					'			<li><label><?php echo 'Title';?></label><input type="text" size="80" id="article_title_' + row.article_id + '" value="' + row.title + '" /></li>' +
					'			<li><label><?php echo 'Image';?></label><input type="text" size="80" id="article_image_' + row.article_id + '" value="' + row.image + '" /></li>' +
					'			<li><label><?php echo 'Category';?></label><input type="hidden" class="article_category" id="article_category_' + row.article_id + '" value="' + row.article_category_id + '" /><button id="article_category_button_' + row.article_id + '">' + row.category_title + '</button></li>' +
					'			<li><label><?php echo $this->translate('Published'); ?></label><select class="article_published" id="article_published_' + row.article_id + '">' +
					'				<option value="yes"' + (row.published == 'yes' ? 'selected="selected"' : '') + '>' + strYes +'</option>' +
					'				<option value="no"' + (row.published == 'no' ? 'selected="selected"' : '') + '>' + strNo +'</option>' +
					'				<option value="archived"' + (row.published == 'archived' ? 'selected="selected"' : '') + '>' + strArchived +'</option>' +
					'			</select></li></ul>' +
					'			<div class="editor" id="article_description_' + row.article_id + '">' + row.description + '</div>' +
					'		</td>' + 
					'	</tr>' + 
					'</tbody>'
				);
				
				$('#article_category_button_' + row.article_id).click(function(ev) {
				    var id = $(this).attr('id').replace('article_category_button_', '');
				    $('#article_category_dialog .selected_article_id').val(id);
				    $('#article_category_dialog').dialog('open');
				});
			});

			rebindArticleForm();
		}
		
		function rebindArticleForm() {
			$('#frmArticles .table-data .editor').each(function (i, obj) {
				var content = $(obj).html();
				$(obj).wymeditor({
					html: content,
					postInit: function(wym) {
						
						//construct the button's html
						var html = "<li class='wym_tools_newbutton'>"
							+ "<a name='SaveButton' href='#'"
							+ " style='background-image:"
							+ " url(/scripts/jquery/wymeditor/skins/default/icons.png); background-position: 0px -" + (26 * 24) + "px;' title='Save'>"
							+ "Save"
							+ "</a></li>";
					
						//add the button to the tools box
						jQuery(wym._box)
							.find(wym._options.toolsSelector + wym._options.toolsListSelector)
							.prepend(html);
						
							//handle click event
							jQuery(wym._box)
								.find('li.wym_tools_newbutton a').click(function() {
									//do something
									var htmlData = wym.html();
									var article_id = jQuery(this).parent().parent().parent().parent().parent().parent().find('.editor').attr('id').replace('article_description_', '');
									var article_title = jQuery('#article_title_' + article_id).val();
									var article_published = jQuery('#article_published_' + article_id).val();

									var subRow = $('#article_description_' + article_id).parent().parent();
									var row = subRow.prev();

									row.find('.article_title').html(article_title);
									
									jQuery.getJSON(
										'/admin/articles/json-update',
										{
											article_id: article_id,
											description: htmlData,
											title: article_title,
											published: article_published
										},
										function (reply) {
											var responseColor = '';
											var subRow = $('#article_description_' + reply.article_id).parent().parent();
											var row = subRow.prev();
											
											if (reply.result == 'ok') {
												responseColor = '#0c0';
												row.find('.article_date_created').html('<div>' + reply.date_created + '</div><div class="small-text">' + reply.date_modified + '</div>');
											} else {
												responseColor = '#c00';
												$('#articles_msg_dialog').show().html('<div class="ui-state-error ui-corner-all">' + reply.data + '</div>').delay(5000).fadeOut();
											}
											var bgColor = subRow.css('background-color');
											
											subRow.css('background-color', responseColor);
											subRow.animate({backgroundColor: bgColor}, 3000, function(){});
										}
									);
									
									return(false);
								});
					}
				});
			});
		}
		
		$('#frmArticles').tableSort({
			onJsonSuccess: renderTable,
			pageIndex: 1,
			rowCount: 5
		});

		
		$('#new_article_description').wymeditor({
			postInit: function(wym) {
				
				//construct the button's html
				var html = "<li class='wym_tools_newbutton'>"
					+ "<a name='SaveButton' href='#'"
					+ " style='background-image:"
					+ " url(/scripts/jquery/wymeditor/skins/default/icons.png); background-position: 0px -" + (26 * 24) + "px;' title='Save'>"
					+ "Save"
					+ "</a></li>";
			
				//add the button to the tools box
				jQuery(wym._box)
					.find(wym._options.toolsSelector + wym._options.toolsListSelector)
					.prepend(html);
				
					//handle click event
					jQuery(wym._box)
						.find('li.wym_tools_newbutton a').click(function() {
							//do something
							var htmlData = wym.html();
							
							var article_title = jQuery('#new_article_title').val();
							var article_image = jQuery('#new_article_image').val();
							
							jQuery.getJSON(
								'/admin/articles/json-create',
								{
									article_container_id: 1,
									description: htmlData,
									title: article_title,
									image: article_image
								},
								function (reply) {
									if (reply > 0) {
                                                                            $('#frmArticles').tableSort('load', null);

                                                                            jQuery('#new_article_title').val('');
                                                                            jQuery('#new_article_image').val('');
                                                                            wym.html('');

									} else {
										alert('<?php echo $strInternalError; ?>');
									}
								}
							);
							
							return(false);
						});
			}
		});

		$('#article_category_dialog').dialog({
		    autoOpen: false,
		    modal: true
		});

		$.jstree._themes = "/scripts/jquery/jstree/themes/";
		$('#article_category_dialog .category_tree').jstree({
		    "plugins" : ["themes", "json_data", "crrm", "ui"],
		    callback: {
			oncreate    : function(NODE,REF_NODE,TYPE,TREE_OBJ) { alert('hi'); },
		    },
		    "ui" : {
			"initially_select" : [ "category_0" ],
		    },
		    "json_data" : {
			"data" : <?php echo Zend_Json::encode($rootCategories);?>,
			"ajax" : {
			    "url" : "/admin/category/json-dir/",
			    "data" : function (n) {
				
				return {
				    "id" : n.attr('id').replace('category_', '')
				};
			    }
			}
		    },
		   
		});

		$('#category_add').click(function(ev){
		    $("#article_category_dialog .category_tree").jstree(
			"create",
			"#category_0",
			"first",
			"Enter a new name"
		    );
		    
		});

	});
</script>
<div id="article_category_dialog" style="display: none;">
    <input type="hidden" class="selected_article_id" value="" />
    <div class="category_tree"></div>
    <button id="category_add">+</button><button id="category_remove">-</button>
</div>
<div id="articles_msg_dialog"></div>

<form id="frmArticles" action="/admin/articles/json.list">
	<table cellspacing="0" cellpadding="0" border="0" class="table-data">
		<tr class="table-header">
			<th><a href="#date_created"><?php echo $t->_('Date Created'); ?></a></th>
			<th>
				<a href="#title"><?php echo $t->_('Article'); ?></a>
			</th>
		</tr>
	</table>
</form>
<br />
<br />
<h3><?php echo $t->_('Create a new article'); ?></h3>
<div>
	<ul class="form-list">
		<li>
			<label for="new_article_title"><?php echo $t->_('Title:'); ?></label>
			<input type="text" id="new_article_title" value="" />
		</li>
		<li>
			<label for="new_article_image"><?php echo $t->_('Image:'); ?></label>
			<input type="text" id="new_article_image" value="/images/dummy.png" />
		</li>
	</ul>
	<div id="new_article_description"></div>
</div>