<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Articles
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. All rights reserved.
 * @license Creative Commons license - See public/license.txt
 */ 
?>
<?php if ($this->pageCount): ?> 

	<div class="paginationControl">
	<!-- Previous page link --> 
	<?php if (isset($this->previous)): ?> 
	  <a href="<?= $this->url(array('start_index' => $this->previous)); ?>">&lt; Previous</a> | 
	<?php else: ?> 
	  <span class="disabled">&lt; Previous</span> | 
	<?php endif; ?> 

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?> 
	  <?php if ($page != $this->current): ?>
	    <a href="<?= $this->url(array('start_index' => $page)); ?>"><?= $page; ?></a> | 
	  <?php else: ?>
	    <?= $page; ?> | 
	  <?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link --> 
	<?php if (isset($this->next)): ?> 
	  <a href="<?= $this->url(array('start_index' => $this->next)); ?>">Next &gt;</a>
	<?php else: ?> 
	  <span class="disabled">Next &gt;</span>
	<?php endif; ?> 
	</div> 
	
<?php endif; ?>