<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Admin_Articles
 * @category Admin
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. All rights reserved.
 * @license Creative Commons license - See public/license.txt
 */

$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = $vars['params'];

if (isset($vars['enable_dojo']) && $vars['enable_dojo'])
{
	$this->dojo()->enable()
		->setDjConfigOption('parseOnLoad', true);
}
if (isset($vars['content'])) echo $vars['content'];

// Menu
$config = array(
	'All' => 		array('id'=>'mnuAdminArticleAll', 'class'=>'menuItem', 'url'=>'/admin/articles/'),
	'New' => 		array('id'=>'mnuAdminArticleNew', 'class'=>'menuItem', 'url'=>'/admin/articles/new/'),
	'Types' =>		array('id'=>'mnuAdminArticleTypes', 'class'=>'menuItem', 'url'=>'/admin/articles/types/'),
	'Categories' => array('id'=>'mnuAdminArticlesCategories', 'class'=>'menuItem', 'url'=>'/admin/articles/categories/')
);
echo new Zre_Ui_Menu('mnuOptions', $config);

// Form
$form = new Zre_Ui_Form_Article_Types();

$isSubmitted = $params['is_submitted'];

if ($isSubmitted == 1 && $form->isValid($params)) {
	$submitAction = $params['submit_action'];
	
	switch ($submitAction) {
		case 'new':
			Zre_Dataset_Article_Resource_Type::create( $params['type'] );
			break;
		case 'update':
			Zre_Dataset_Article_Resource_Type::update( $params );
			break;
		case 'delete':
			Zre_Dataset_Article_Resource_Type::delete( $params['type'] );
			break;
		default:
			?>
			<div class="error"><?php echo $t->_('Invalid action.'); ?></div>
			<?php 
			break;
	}
	$form = new Zre_Ui_Form_Article_Types();
}
$form->setAttrib('id', 'frmTypes');
$form->setAction('/admin/articles/types/');

$form->getElement('New')->setAttrib('onclick', 
	"JavaScript: void(document.getElementById('submit_action').value='new');
				 void(document.getElementById('frmTypes').submit());");

$form->getElement('Update')->setAttrib('onclick', 
	"JavaScript: void(document.getElementById('submit_action').value='update');
				 void(document.getElementById('frmTypes').submit());");
$form->getElement('Delete')->setAttrib('onclick', 
	"JavaScript: document.getElementById('submit_action').value='delete';
				 document.getElementById('frmTypes').submit(); alert(); ");

echo $form;
?>