<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Articles
 * @subpackage Articles_Read
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$vars = $this->getVars();
$params 	= $vars['params'];

$articleTitleText = '';
$article = new Zre_Dataset_Article();

if (is_numeric($params['id'])) {
	$data = $article->read( $params['id'] )->current()->toArray();
	$articleTitleText = $data['title'] . ' - ';
}

$this->headTitle($articleTitleText . (string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

if (isset($vars['content'])) echo $vars['content'];


$node_id 	= isset($params['id']) ? $params['id'] : 1;

//$articleDatagrid = new Zre_Ui_Datagrid_Read_Article($node_id);
//
//$articleData = $articleDatagrid->getData();
//
$articleData = $article->read( $node_id );

if ($articleData->count() > 0) {
	$articleData = $articleData->current()->toArray();
	$articleId 			= $articleData['article_id'];
	$articleContainerId = $articleData['article_container_id'];
	$articleResource 	= $articleData['resource'];
	$articlePublished 	= $articleData['published'];
	$articleTitle 		= stripslashes($articleData['title']);
	$articleDescription = stripslashes($articleData['description']);
	$articleDateCreated  = new Zend_Date( $articleData['date_created'] );
	$articleDateModified = new Zend_Date( $articleData['date_modified'] );
	$articleImage 		= $articleData['image'];
	
	if (!$articleImage) $articleImage = '/images/dummy.png';
	
//	$articleData['content'] = str_replace(array('{', '}'), array('<', ' />'), $articleData['content']);
//	$articleContent = ( $articleData['use_zre_plugins'] == 'yes' ? Plugin::search_and_insert( $articleData['content'] ) : $articleData['content'] );
} else {
	$articleId 			= 1;
	$articleContainerId = 1;
	$articleResource 	= '';
	$articlePublished 	= '';
	$articleTitle 		= $t->_('Page Not Found');
	$articleDescription = $t->_('The requested article was not found.');
	$articleDateCreated  = new Zend_Date();
	$articleDateModified = new Zend_Date();
	$articleImage 		= '/images/dummy.png';
	
	$articleContent = '';
}
$titleSlug = Zre_Template::createSlug($articleTitle);
?>
<div class="articleContainer">
	<table cellspacing="0" cellpadding="0" border="0" class="articleContainerInner">
		
		<tr>
			<td class="articleImageCell">
				<img src="<?php echo $articleImage; ?>" alt="<?php echo $articleTitle; ?>" class="articleImage" />
			</td>
			
			<td class="articleText">
				<h2 class="articleTitle">
					<a name="article-<?php echo $articleId; ?>" href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'id'=>$articleId, 'title' => $titleSlug), 'indexReadArticle'); ?>">
						<?php echo $articleTitle; ?>
					</a>
				</h2>
				<div class="articleDescription">
				<?php echo Plugin::search_and_insert($articleDescription); ?>
				</div>
				<div class="articleFooter"><?php echo $t->_('Last edited ') . $articleDateCreated->getArpa(); ?></div>
			</td>
		</tr>
	</table>
</div>

<a 	class="lightLink" 
	href="<?php echo $this->url(array('controller' => 'read', 'action' => 'index')); ?>">
	<?php echo $t->_('Browse Articles'); ?>
</a>