<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Articles
 * @subpackage Articles_Index
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = $vars['params'];

if (isset($vars['content'])) echo $vars['content'];

echo $this->form;
?>
<?php

	/**
	 * Grab our article data. retrieve articles from the root category,
	 * and only grab published articles. We dont care about the resource
	 * type here.
	 * 
	 */
	$categoryParentId = isset($params['c']) ? $params['c'] : null;
	if (!is_numeric($categoryParentId)) $categoryParentId = 1;
	
	$articleContainer = new Zre_Dataset_Article_Container();
	$article = new Zre_Dataset_Article();
	
	$mainCategory = $articleContainer->read( $categoryParentId );
	
	$where = null;
	if (isset($categoryParentId)) {
		$where = array('parent_id' => $categoryParentId);
	}
	$categories = $articleContainer->listAll( $where );
?>
<h1 class="articleCategoryTitle"><?php echo $t->_('Category:'); ?> <?php echo $mainCategory->current()->title;?></h1>
<?php 
//$readArticle = new Zre_Ui_Datagrid_Read($categoryParentId, 'yes', null);
	if (isset($categoryParentId)) {
		$readArticle = $article->listAll( array('article_container_id' => $categoryParentId) );
	} else {
		$readArticle = $article->listAll();
	}
	
	foreach($readArticle as $index => $a) {
		
		// ...Grab our article properties
		$a = (object) $a;
		$articleId 			= $a->article_id;
		$articleContainerId = $a->container_id;
		$articleResource 	= $a->resource;
		$articlePublished 	= $a->published;
		$articleTitle 		= $a->title;
		$articleDescription = $a->description;
		$articleDateCreated  = new Zend_Date( $a->date_created );
		$articleDateModified = new Zend_Date( $a->date_modified );
		$articleImage 		= $a->image;
		
		$articleDescription = html_entity_decode($articleDescription, ENT_QUOTES);
		$articleDescription = str_replace(array('{', '}', '\"'), array('<', ' />', '"'), $articleDescription);
		
		$titleSlug = Zre_Template::createSlug($articleTitle);
		
		if (empty($articleImage)) $articleImage = '/images/dummy.png';
		// ...And display however we want.
?>
		<div class="articleContainer">
			<table cellspacing="0" cellpadding="0" border="0" class="articleContainerInner">
				
				<tr>
					<td class="articleImageCell">
						<a href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'id'=>$articleId, 'title' => $titleSlug), 'indexReadArticle'); ?>" class="articleImageAnchor"><img src="<?php echo $articleImage; ?>" alt="<?php echo $articleTitle; ?>" class="articleImage" /></a>
					</td>
					
					<td class="articleText">
						<h2 class="articleTitle">
							<a name="article-<?php echo $articleId; ?>" href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'id'=>$articleId)); ?>">
								<?php echo $articleTitle; ?>
							</a>
						</h2>
						<div class="articleSubHeader"><?php echo $t->_('Summary'); ?></div>
						<div class="articleDescription">
						<?php echo Plugin::search_and_insert($articleDescription); ?>&nbsp;<a href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'id'=>$articleId, 'title' => $titleSlug), 'indexReadArticle'); ?>"><?php echo $t->_('...more'); ?></a>
						</div>
						<div class="articleFooter"><?php echo $t->_('Written on ') . $articleDateCreated->getArpa(); ?></div>
					</td>
				</tr>
			</table>
		</div>
<?php 
	}

	foreach ($categories as $category) {
		if ($category['article_container_id'] != $categoryParentId ) {
			$readArticle = Zre_Dataset_Article::readContainerArticles($category['article_container_id']);
			$totalArticles = count($readArticle);
			
			if ($totalArticles < 1) continue;
?>
	<h2 class="articleSubCategoryTitle"><a href="/read/index/c/<?php echo $category['article_container_id'];?>"><?php echo $category['title']; ?></a></h2>
<?php
			foreach($readArticle as $index => $article) {
				
				// ...Grab our article properties
				$articleId 			= $article['article_id'];
				$articleContainerId = $article['article_container_id'];
				$articleResource 	= $article['resource'];
				$articlePublished 	= $article['published'];
				$articleTitle 		= $article['title'];
				$articleDescription = $article['description'];
				$articleDateCreated  = new Zend_Date( $article['date_created'] );
				$articleDateModified = new Zend_Date( $article['date_modified'] );
				$articleImage 		= $article['image'];
				
				$articleDescription = html_entity_decode($articleDescription, ENT_QUOTES);
				$articleDescription = str_replace(array('{', '}', '\"'), array('<', ' />', '"'), $articleDescription);
				
				if (empty($articleImage)) $articleImage = '/images/dummy.png';
				// ...And display however we want.
?>
				<div class="articleContainer">
					<table cellspacing="0" cellpadding="0" border="0" class="articleContainerInner">
						
						<tr>
							<td class="articleImageCell">
								<a href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'article_id'=>$articleId)); ?>" class="articleImageAnchor"><img src="<?php echo $articleImage; ?>" alt="<?php echo $articleTitle; ?>" class="articleImage" /></a>
							</td>
							
							<td class="articleText">
								<a name="article-<?php echo $articleId; ?>" href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'article_id'=>$articleId)); ?>">
									<h2 class="articleTitle"><?php echo $articleTitle; ?></h2>
								</a>
								<div class="articleSubHeader"><?php echo $t->_('Summary'); ?></div>
								<div class="articleDescription">
								<?php echo Plugin::search_and_insert($articleDescription); ?>&nbsp;<a href="<?php echo $this->url(array('controller'=>'read', 'action'=>'article', 'article_id'=>$articleId)); ?>"><?php echo $t->_('...more'); ?></a>
								</div>
								<div class="articleFooter"><?php echo $t->_('Written on ') . $articleDateCreated->getArpa(); ?></div>
							</td>
						</tr>
					</table>
				</div>
<?php 
			}
		}
	}
?>