<?php
/**
 * ZRECommerce e-commerce web application.
 *
 * @author ZRECommerce
 *
 * @package Admin
 * @subpackage Users
 * @category Core
 *
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */
$settings = ZRE_Config::getSettingsCached();

$this->headTitle((string) $settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title))
    $this->title = (string) $settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();

if (isset($vars['content']))
    echo $vars['content'];

$strPassword = $this->translate('Password');
$strPasswordMatch = $this->translate('Password (again)');
$strChangePassword = $this->translate('Change Password');

$strFirstAndLastName = $this->translate('First and Last Name');
$strDateOfBirth = $this->translate('Date of Birth');
$strRole = $this->translate('Role');
$strCity = $this->translate('City');
$strState = $this->translate('State');
$strZipcode = $this->translate('Zipcode');
$strCountry = $this->translate('Country');
$strUpdateProfile = $this->translate('Update Profile');

$roles = new Zre_Dataset_Acl_Role();
$optionRoles = '';
$jsonRoles = '';
$arrRoles = array();

$data = $roles->listAll(null, array('order' => 'name ASC'));

foreach ($data as $row) {
    $row = (object) $row;
    $optionRoles .= '<option value="' . $row->acl_role_id . '">' . $row->name . '</option>';
    $arrRoles[$row->acl_role_id] = $row->name;
}

$jsonRoles = Zend_Json::encode($arrRoles);

/**
 * @todo implement pagination jquery plugin.
 */
?>
<script type="text/javascript">
jQuery(document).ready(function($){
    var jsonRoles = <?php echo $jsonRoles ?>;

    $('#btnCreateUser').click(function(ev){
	ev.preventDefault();
	// ...Create a user via getJSON()

	var user_name = $('#new_user_name');
	var first_name = $('#new_user_first_name');
	var last_name = $('#new_user_last_name');
	var date_of_birth = $('#new_user_date_of_birth');

	var email = $('#new_user_email');
	var role = $('#new_user_role');
	var city = $('#new_user_city');
	var state_province = $('#new_user_state_province');
	var zipcode = $('#new_user_zipcode');
	var country = $('#new_user_country');

	$.getJSON(
	'/admin/users/json-create',
	{
	    name: user_name.val(),
	    first_name: first_name.val(),
	    last_name: last_name.val(),
	    date_of_birth: date_of_birth.val(),
	    email: email.val(),
	    role: role.val(),
	    city: city.val(),
	    state_province: state_province.val(),
	    zipcode: zipcode.val(),
	    country: country.val()
	},
	function (reply) {
	    try {
		if (reply.result == 'ok') {
		    $.getJSON(
			    '/admin/users/json-list',
			    null,
			    renderTable
		    );
		} else {
		    alert(reply.data);
		}
	    } catch (e) {
		    alert(e.toString());
	    }
	});
    });

    $('#frmUsers').tableSort({
	pageIndex: 1,
	rowCount: 5,
	onJsonSuccess: renderTable
    });

    function renderTable(response){
	    if (response.result == 'ok') {
		var strChangePassword = '<?php echo $strChangePassword; ?>';
		var strUpdateProfile = '<?php echo $strUpdateProfile; ?>';

		$('#frmUsers .table-data .table-body').remove();

		$.each(response.data, function(i, row){

		    $('#frmUsers .table-data').append(
		    '<tbody class="table-body">' +
			    '<tr class="table-row">' +
			    '	<td>' + row.user_id + '</td>' +
			    '	<td>' + row.name + '</td>' +
			    '	<td>' + row.email + '</td>' +
			    '	<td>' + jsonRoles[row.role] + '</td>' +
			    '	<td>' + row.city + '</td>' +
			    '	<td>' + row.state_province + '</td>' +
			    '	<td>' + row.zipcode + '</td>' +
			    '	<td>' + row.country + '</td>' +
			    '</tr>' +
			    '<tr class="table-sub-row">' +
			    '	<td colspan="3" style="vertical-align: top">' +
			    '		<ul class="form-list">' +
			    '			<li><label><?php echo $strPassword; ?>:</label><input type="password" id="user_password_' + row.user_id + '" class="user-password" value="" /></li>' +
			    '			<li><label><?php echo $strPasswordMatch; ?>:</label><input type="password" id="user_password_match_' + row.user_id + '" class="user-password-match" /></li>' +
			    '			<li><input type="button" value="' + strChangePassword + '" class="change-password-button" /></li>' +
			    '		</ul>' +
			    '	</td>' +
			    '	<td colspan="5" style="vertical-align: top;">' +
			    '		<ul class="form-list">' +
			    '			<li><label><?php echo $strFirstAndLastName; ?></label><input type="text" id="user_first_name_' + row.user_id + '" class="user-first-name" value="' + row.first_name + '" /><input type="text" id="user_last_name_' + row.user_id + '" class="user-last-name" value="' + row.last_name + '" /></li>' +
			    '			<li><label><?php echo $strDateOfBirth; ?></label><input type="text" id="user_date_of_birth_' + row.user_id + '" class="user-date-of-birth" value="' + row.date_of_birth + '" /></li>' +
			    '			<li><label><?php echo $strRole; ?></label><select id="user_role_' + row.user_id + '" class="user-role"><?php echo $optionRoles; ?></select></li>' +
			    '			<li><label><?php echo $strCity; ?></label><input type="text" id="user_city_' + row.user_id + '" class="user-city" value="' + row.city + '" /></li>' +
			    '			<li><label><?php echo $strZipcode; ?></label><input type="text" id="user_zipcode_' + row.user_id + '" class="user-zipcode" value="' + row.state_province + '" /></li>' +
			    '			<li><label><?php echo $strState; ?></label><input type="text" id="user_state_province_' + row.user_id + '" class="user-state-province" value="' + row.zipcode + '" /></li>' +
			    '			<li><label><?php echo $strCountry; ?></label><input type="text" id="user_country_' + row.user_id + '" class="user-country" value="' + row.country + '" /></li>' +
			    '			<li><input type="button" value="' + strUpdateProfile + '" class="update-profile-button" /></li>' +
			    '		</ul>' +
			    '	</td>' +
			    '</tr>' +
			    '</tbody>'
		    );

		    $('#frmUsers .table-data #user_role_' + row.user_id)
			.find("option[value='" + row.role + "']")
			.attr('selected', 'selected');

		    $('#frmUsers .table-data .change-password-button').each(function(i, obj){
			$(obj).click(function(ev) {
			    var formList = $(this).parent().parent();

			    var password = $(formList.find('.user-password'));
			    var password_match = $(formList.find('.user-password-match'));

			    var user_id = password.attr('id').replace('user_password_', '');

			    $.getJSON(
			    '/admin/users/json-update/',
			    {
				user_id: user_id,
				password: password.val(),
				password_match: password_match.val()
			    },
			    function (reply) {
				if (reply.result == 'error') {
				    alert(reply.data);
				} else {
				    var lastColor = formList.parent().css('background-color');
				    formList.parent().css(
					    'background-color', '#0c0'
				    );
				    formList.parent().animate(
					    {
						    backgroundColor: lastColor
					    },
					    3000,
					    function(){}
				    );
				}
			    });
			});
		    });

		    $('#frmUsers .table-data .update-profile-button').each(function(i, obj){
			$(obj).click(function(ev) {
			    var formList = $(this).parent().parent();

			    var first_name = $(formList.find('.user-first-name'));
			    var last_name = $(formList.find('.user-last-name'));
			    var date_of_birth = $(formList.find('.user-date-of-birth'));
			    var role = $(formList.find('.user-role'));
			    var city = $(formList.find('.user-city'));
			    var state_province = $(formList.find('.user-state-province'));
			    var zipcode = $(formList.find('.user-zipcode'));
			    var country = $(formList.find('.user-country'));

			    var user_id = role.attr('id').replace('user_role_', '');

			    $.getJSON(
			    '/admin/users/json-update/',
			    {
				user_id: user_id,
				first_name: first_name.val(),
				last_name: last_name.val(),
				date_of_birth: date_of_birth.val(),
				role: role.val(),
				city: city.val(),
				state_province: state_province.val(),
				zipcode: zipcode.val(),
				country: country.val()
			    },
			    function (reply) {
				if (reply.result == 'error') {
					alert(reply.data);
				} else {
				    var lastColor = formList.parent().css('background-color');
				    formList.parent().css(
					'background-color', '#0c0'
				    );
				    formList.parent().animate(
					{
						backgroundColor: lastColor
					},
					3000,
					function(){}
				    );
				}
			    });
			});
		    });

		});
	    } else {
		    alert('Error: ' + response.data);
	    }
    }

    $('#frmCreateUser').dialog({
	autoOpen: false,
	modal: true,
	minWidth: 500,
	width: 500
    });

    $('.create-new-user-button').click(function(ev){
	ev.preventDefault();
	$('#frmCreateUser').dialog('open');
	return false;
    });
});
</script>

<input type="button" class="create-new-user-button" value="<?php echo $this->translate('New User'); ?>" />

<form id="frmUsers" action="/admin/users/json.list">
    <table cellspacing="0" cellpadding="0" border="0" class="table-data">
	<tr class="table-header">
	    <th><a href="#user_id">ID</a></th>
	    <th><a href="#name">User</a></th>
	    <th><a href="#email">E-Mail</a></th>
	    <th><a href="#role">Role</a></th>
	    <th><a href="#city">City</a></th>
	    <th><a href="#state_province">State</a></th>
	    <th><a href="#zipcode">Zip</a></th>
	    <th><a href="#country">Country</a></th>
	</tr>
    </table>
</form>

<input type="button" class="create-new-user-button" value="<?php echo $this->translate('New User'); ?>" />

<div id="frmCreateUser" title="<?php echo $this->translate('New User'); ?>">
    <ul class="form-list small-text">
	<li>
	    <label for="new_user_name"><?php echo $this->translate('User Name'); ?></label>
	    <input type="text" id="new_user_name" value="" />
	</li>
	<li>
	    <label for="new_user_first_name"><?php echo $this->translate('First and Last Name'); ?></label>
	    <input type="text" id="new_user_first_name" value="" />
	    <input type="text" id="new_user_last_name" value="" />
	</li>
	<li>
	    <label for="new_user_date_of_birth"><?php echo $this->translate('Date of Birth (YYYY-MM-DD)'); ?></label>
	    <input type="text" id="new_user_date_of_birth" value="" />
	</li>
	<li>
	    <label for="new_user_email"><?php echo $this->translate('E-Mail'); ?></label>
	    <input type="text" id="new_user_email" value="" />
	</li>
	<li>
	    <label for="new_city"><?php echo $this->translate('City, State/Province, Zip'); ?></label>
	    <input type="text" id="new_user_city" value="" style="width: 6em;" />
	    <input type="text" id="new_user_state_province" value="" style="width: 2.2em;" />
	    <input type="text" id="new_user_zipcode" value="" style="width: 5.2em;" />
	</li>
	<li>
	    <label for="new_user_country"><?php echo $this->translate('Country (2-Letter)'); ?></label>
	    <input type="text" id="new_user_country" value="" style="width: 2.2em;" />
	</li>
	<li>
	    <label for="new_user_role"><?php echo $this->translate('Role'); ?></label>
	    <select id="new_user_role">
		<?php
		echo $optionRoles;
		?>
	    </select>
	</li>
    </ul>
    <input type="button" id="btnCreateUser" value="<?php echo 'New User'; ?>" />
</div>