<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Logs
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = ZRE_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = isset($vars['params']) ? $vars['params'] : null;

$pageIndex = isset($params['page']) ? $params['page'] : 1;
$rowCount = isset($params['rowCount']) ? $params['rowCount'] : 50;

if (isset($vars['content'])) echo $vars['content'];

$options = array(
	'limit' => array(
		'page' => $pageIndex,
		'rowCount' => $rowCount
	)
);

$priorityToString = array(
	'LOG_EMERG' => 0,
	'LOG_ALERT' => 1,
	'LOG_CRIT' => 2,
	'LOG_ERR' => 3,
	'LOG_WARNING' => 4,
	'LOG_NOTICE' => 5,
	'LOG_INFO' => 6,
	'LOG_DEBUG' => 7
//	'LOG_KERN' => 0,
//	'LOG_USER' => 8,
//	'LOG_MAIL' => 16,
//	'LOG_DAEMON' => 24,
//	'LOG_AUTH' => 32,
//	'LOG_SYSLOG' => 40,
//	'LOG_LPR' => 48,
//	'LOG_NEWS' => 56,
//	'LOG_UUCP' => 64,
//	'LOG_CRON' => 72,
//	'LOG_AUTHPRIV' => 80,
//	'LOG_LOCAL0' => 128,
//	'LOG_LOCAL1' => 136,
//	'LOG_LOCAL2' => 144,
//	'LOG_LOCAL3' => 152,
//	'LOG_LOCAL4' => 160,
//	'LOG_LOCAL5' => 168,
//	'LOG_LOCAL6' => 176,
//	'LOG_LOCAL7' => 184,
//	'LOG_PID' => 1,
//	'LOG_CONS' => 2,
//	'LOG_ODELAY' => 4,
//	'LOG_NDELAY' => 8,
//	'LOG_NOWAIT' => 16,
//	'LOG_PERROR' => 32
);
$priorityToString = array_flip($priorityToString);

Zre_Dataset_Logs::init();
if (isset($params['is_submitted']) && $params['is_submitted'] == '1') {
	$results = array();
	foreach($params['deleteLog'] as $id => $log) {
		$deleteResult = Zre_Dataset_Logs::delete('id = ?', $id);
		$results[] = 'Delete log id #' . $id . ': ' . ($deleteResult ? '<i class="ok">OK</i>' : '<i class="error">FAIL</i>');
	}
	echo "<b>" . implode("<br />\n", $results) . "</b>";
}
$allLogs = Zre_Dataset_Logs::listAll(null, $options);
?>
<form id="logs" method="post">
<input type="hidden" name="is_submitted" value="1" />
<table cellspacing="2px" cellpadding="0px" border="1px">
  <tr>
  	<th>Delete?</th>
    <th>Date</th>
    <th>Desc</th>
    <th>Priority</th>
  </tr>
<?php 
	foreach($allLogs as $log) {
	?>
	<tr>
		<td><input id="deleteLog_<?php echo $log['id']?>" name="deleteLog[<?php echo $log['id']?>]" type="checkbox" /></td>
		<td><?php echo $log['date']?></td>
		<td><pre><?php echo $log['message']?></pre></td>
		<td><?php echo $priorityToString[$log['priority']]?></td>
	</tr>
	<?php 
	}
?>
</table>
<input type="Submit" value="<?php echo $t->_('Submit')?>" />
</form>