<?php
/**
 * ZRECommerce e-commerce web application.
 * 
 * @author ZRECommerce
 * 
 * @package Admin
 * @subpackage Search_Settings
 * @category Core
 * 
 * @version $Id$
 * @copyright Copyrights 2008 ZRECommerce. See README file.
 * @license GPL v3 or higher. See README file.
 */

$settings = Zre_Config::getSettingsCached();
$t = Zend_Registry::get('Zend_Translate');

$this->headTitle((string)$settings->site->title, Zend_View_Helper_Placeholder_Container_Abstract::SET);
if (empty($this->title)) $this->title = (string)$settings->site->title;
$this->placeholder('title')->set($this->title);

$vars = $this->getVars();
$params = $vars['params'];

if (isset($vars['content'])) echo $vars['content'];

$form = new Zre_Ui_Form_Dialog_YesNoAbort(null, 'Would you like to index your website articles and products?');

$isSubmitted = isset($params['is_submitted']);
$formResponse = isset($params['yes_no_abort']) ? $params['yes_no_abort'] : '';

if ($isSubmitted == 1) {
	switch ($formResponse) {
		case 'yes':
			if (Zre_Search::flush() ){
				
				echo "<h3>" . $t->_('Flush complete.') . "</h3>";
			}
			
			try {
				Zre_Search::index();
				echo "<h3>" . $t->_('Indexing complete.') . "</h3>" . "<a href=\"/admin/\">" . $t->_('Back to dashboard') . "</a>";
			} catch (Exception $e ) {
				echo "<h3>" . $t->_('Indexing failed - Could not flush index data.') . "</h3>" . "<a href=\"/admin/\">" . $t->_('Back to dashboard') . "</a>";
			}
			break;
		default:
			echo "<h3>" . $t->_('Indexing cancelled - No changes made') . "</h3>" . "<a href=\"/admin/\">" . $t->_('Back to dashboard') . "</a>";
			break;
	}
} else {

	echo $form;
}
?>